services:
  skillforge-db:
    image: postgres:17
    container_name: skillforge-db
    hostname: skillforge-db
    environment:
      POSTGRES_USER: ${SKILLFORGE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SKILLFORGE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SKILLFORGE_POSTGRES_DBNAME}
      TZ: ${SKILLFORGE_TIMEZONE}
    ports:
      - "${SKILLFORGE_POSTGRES_PORT}:5432"
    volumes:
      - skillforge-db:/var/lib/postgresql/data
    networks:
      - skillforge

volumes:
  skillforge-db:
    driver: local
    name: skillforge-db

networks:
  skillforge:
    driver: bridge
    name: skillforge
